/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppHome {
    'nu': number;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'nu'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
